### ISSUE TITLE
Consul complaining about TCP/8301 being blocked to Vault

### ISSUE THREAD

**Issue by andysnowden** [hashicorp/terraform-aws-vault#110]
I deployed consul/vault using the modules provided by this and the consul repos and everything is working correctly.  However when adding monitoring to consul I noticed all nodes in the cluster were emitting the following error

`2018/11/05 19:31:07 [ERR] memberlist: Push/Pull with i-abcefg12345 failed: dial tcp 1.1.1.1:8301: i/o timeout`

I changed the IP for security reasons but it was one of the consul-clients running along side of the vault nodes.  Looking at the default SG produced by "vault-security-group-rules" it's now allowing TCP/8301 from the consul SG/subnet.

Is this by design?  I know this is the SERF Lan port but is there any harm in allowing it?

**Comment by cytopia** [comment]
@andysnowden FYI: there's also a much more general question open regarding all security group settings to figure out which ones are actually required and which ones are optional: https://github.com/hashicorp/terraform-aws-vault/issues/107#issuecomment-432304426

**Comment by brikis98** [comment]
If you are running a Consul agent as a client, you should add the Consul client security group to your server(s): https://github.com/hashicorp/terraform-aws-consul/tree/master/modules/consul-client-security-group-rules

**Comment by andysnowden** [comment]
> If you are running a Consul agent as a client, you should add the Consul client security group to your server(s): https://github.com/hashicorp/terraform-aws-consul/tree/master/modules/consul-client-security-group-rules. This includes the 8301 port for SERF lan.

Thanks,

Looks like I missed that in the terraform example while integrating it with our existing stuff.
