### ISSUE TITLE
Making Pip and Boto Installation Optional

### ISSUE THREAD

**Issue by lawliet89** [hashicorp/terraform-aws-vault#116]
AFAIK, pip and boto was added to the install script as part of the examples in https://github.com/hashicorp/terraform-aws-vault/pull/96

But pip and boto are strictly not required unless you are using the `vault-consul-ami` example. Shouldn't these installation be part of the example packer template for that example instead of being in the `install-vault` module? Alternatively, they can be optional.

More specific to my concern: I am using, by default, Python 3 on my Ubuntu AMIs. I am not sure what kind of issue installing pip and pip packages from Python 2 on top of Python 3 would bring. I am also not using `boto` in my AMI.

**Comment by brikis98** [comment]
That's a good point. @Etiene Thoughts on moving `pip` and `boto` to the example AMI rather than the `install` script?
