### ISSUE TITLE
Installing as a Vault Agent

### ISSUE THREAD

**Issue by linxcat** [hashicorp/terraform-aws-vault#133]
Using the Consul module it is possible to use the run-consul script to start consul in agent mode and allow vault to connect to localhost.

There doesn't appear to be a similar provision in this module, which would allow behaviour shown in the root README diagram in which vault agents connect to the vault servers from the client applications/instances. Am I missing something, or is there missing functionality?

**Comment by brikis98** [comment]
Yes, I think you're right. Vault's agent mode was added relatively recently with the auto auth functionality, and we haven't yet updated the the `run-vault` script with support for it. A PR to do so is very welcome!
