### ISSUE TITLE
terraform 0.12 requires "./" in front of relative module sources

### ISSUE THREAD

**Issue by mildwonkey** [hashicorp/terraform-aws-vault#141]
Sorry to do this out of order - PR #140 fixes this.

Terraform's [documentation](https://www.terraform.io/docs/modules/sources.html#local-paths) specifies that "./" is required for relative module sources. While it was still allowed in Terraform 0.11, it now causes an error in terraform 0.12.

**Comment by brikis98** [comment]
Thanks for the heads up. We have not yet upgraded to Terraform 0.12 as it's still in beta, but hope to do so soon.

**Comment by mildwonkey** [comment]
Sure thing! I also should have specified that this change does not break compatibility with earlier versions of terraform.
