### ISSUE TITLE
Plans for 0.12 support?

### ISSUE THREAD

**Issue by deitch** [hashicorp/terraform-aws-vault#151]
Are there plans for full 0.12 support? There are numerous incompatibilities between 0.11 and 0.12. Including this module in a 0.12 run fails.

Thanks

**Comment by brikis98** [comment]
Yup! Hoping to have this updated by the end of the month.

**Comment by tlinkin** [comment]
Any news on the update status ? The generate tls module is broken by 0.12 as the old lists are in conflict with 0.12

**Comment by tlinkin** [comment]
PR #155 has been submitted for upgrade to 0.12 of tls-cert module

**Comment by mcalhoun** [comment]
#154 Adds support for v0.12 and will be merged shortly!
