### ISSUE TITLE
Ubuntu 18.04 Support

### ISSUE THREAD

**Issue by sharmaanshul21** [hashicorp/terraform-aws-vault#158]
Hi, any ETA on this? If no one is working I am more than happy to send a PR for the same.

**Comment by Etiene** [comment]
Hello! I haven't started on it yet, but it's on my list for this or next week :)

**Comment by Etiene** [comment]
Update: working on it right now #159

**Comment by sharmaanshul21** [comment]
@Etiene thank you.
