### ISSUE TITLE
Allow creating vault clusters and the elb in different subnets

### ISSUE THREAD

**Issue by dmattia** [hashicorp/terraform-aws-vault#174]
In the root module, it is setup so that the ELB module and the Cluster module use the same Subnet tags for looking up which subnets they can exist in:

https://github.com/hashicorp/terraform-aws-vault/blob/master/main.tf#L223-L226

Is it possible to make it so that the vault clusters exist in private subnets, while the ELB is in a public subnet with access to talk to the cluster subnets?

**Comment by brikis98** [comment]
The root folder is an *example* of how to use the modules in this repo. That example is designed to make it easy to learn/experiment (and therefore makes simplifying assumptions, such as what subnets to use), but it is not meant to be used directly for production. If you wish to use this code for production, please use the modules in the `modules` folder directly instead!
