### ISSUE TITLE
Allow adding extra IAM Policies to Vault-Cluster module

### ISSUE THREAD

**Issue by dmattia** [hashicorp/terraform-aws-vault#175]
The Private TLS Cert module has some recommendations for getting encrypted TLS files onto the Vault servers, but most of them require giving the vault servers extra permissions, especially:

```
- Encrypt the certificate using KMS and include the encrypted files in the AMI for your Vault servers. Give those servers an IAM role that lets them access the same KMS key and decrypt their certs just before booting.
- Put your TLS cert in a secure S3 Bucket with encryption enabled. Give your Vault servers an IAM role that allows them to download the certs from the S3 bucket just before booting.
```

But the vault-cluster module does not allow for adding these extra permissions. So for now, we need to fork the module to add in these extra permissions.

**Comment by brikis98** [comment]
The `vault-cluster` module exports the IAM role ID/ARN/name as [output variables](https://github.com/hashicorp/terraform-aws-vault/blob/master/modules/vault-cluster/outputs.tf#L21-L31). You can attach whatever policies you need to this IAM role, e.g., by using the [aws_iam_role_policy resource](https://www.terraform.io/docs/providers/aws/r/iam_role_policy.html) and passing in the IAM role ID output into the `role` input.

**Comment by dmattia** [comment]
That makes a lot of sense, and fully answers my question. Thanks
