### ISSUE TITLE
Is "NoNewPrivileges=yes" in the systemd Vault unit recommended when only running Vault Agent?

### ISSUE THREAD

**Issue by draoncc** [hashicorp/terraform-aws-vault#194]
Currently, the systemd Vault unit includes `NoNewPrivileges=yes` to prevent elevation of privileges. When starting vault with `run-vault --agent` this however also makes it impossible for Vault Agent Template to gain system level control over other services.

Is it considered "safe" to omit the `NoNewPrivileges=yes` when starting vault with `run-vault --agent`?

---

Specifically, I want to use Vault Agent Template to render TLS certificates for Nomad.

/opt/vault/config/default.hcl
```hcl
// vault and auth_auth omitted

template {
  destination = "/opt/nomad/tls/nomad.key.pem"
  perms       = 0600
  command     = "sudo -n systemctl reload nomad.service"
  contents    = <<EOL
{{ with secret "pki_int_nomad/issue/nomad-cluster" "common_name=client.eu-central-1.nomad" "ttl=24h" "ip_sans=10.0.2.222" "alt_name=nomad.foxbase.de" }}
{{- .Data.private_key }}{{ end }}
EOL
}
```

/etc/sudoers.d/20-nomad
```
vault ALL=NOPASSWD: /usr/bin/systemctl reload nomad.service
```

After rendering the template, Vault Agent template.server errors with `sudo: effective uid is not 0`

**Comment by draoncc** [comment]
For anyone stumbling upon this, I solved my issue by instead adding CAP_KILL to Vault's capabilities, and deploying nomad along with a simple binary that sends a SIGHUP to the Nomad process. This binary also has `cap_kill+eip` set, owned by the Vault user, with permissions 600 to prevent unauthorized execution.

Attempting to elevate privileges as described above results in more unexpected, erroneous behavior.

**Comment by kettlebell** [comment]
Thanks heaps, found this issue very helpful. I've taken your approach with one difference: if the vault agent has CAP_KILL specified in AmbientCapabilities the 'simple binary' doesn't need `cap_kill` to be explicitly set as it will inherit the capability from the ambient set.
