### ISSUE TITLE
"/module/vault-cluster" has error with conflicting attributes (vpc_zone_identifier & availability_zones)

### ISSUE THREAD

**Issue by chrismillah** [hashicorp/terraform-aws-vault#209]
Trying to leverage the module 'vault-cluster' and keep hitting an error with conflicting attributes defined in the /terraform-aws-vault/modules/vault-cluster/main.tf on line 17.

Also, none of the examples leveraging the "vault-cluster" module are passing a variable for either vpc_zone_identifier OR availability_zones

A bit confused how any of the examples would work otherwise.

![Screen Shot 2020-08-12 at 6 01 09 PM](https://user-images.githubusercontent.com/6306435/90072648-ce896400-dcc5-11ea-9027-04c0a2aebe8b.png)

**Comment by brikis98** [comment]
I  believe this is due to AWS Provider 3.x coming out recently with backwards incompatible changes. #206 has the fix.
