### ISSUE TITLE
vault-elb module complaining about both SubnetId and AZ being specified

### ISSUE THREAD

**Issue by flapp** [hashicorp/terraform-aws-vault#21]
I'm creating a setup with Vault and Nomad by using the registry modules. 
Vault is being used like this: 

```
module "vault" {
    source = "hashicorp/vault/aws"

    # insert the 5 required variables here
    create_dns_entry = false
    hosted_zone_domain_name = "not-valid.org"
    s3_bucket_name = "${var.vault_s3_bucket_name}"
    force_destroy_s3_bucket = true # Only for testing purposes, for production envs do NOT set this to true
    ssh_key_name = "${aws_key_pair.my-key.key_name}"
    vault_domain_name = "also-not-valid"
    ami_id = "${var.vault_ami_id}"
    consul_cluster_tag_key = "${var.cluster_tag_key}"
    consul_cluster_name = "${var.cluster_name}"
    vault_cluster_name = "${var.cluster_name}-vault"
    aws_region = "${var.aws_region}"
}

```

After the fix from issue #20 , the module now complains about the fact that you can only give one of SubnetIds or AvailabilityZones:

> Error applying plan:
> 
> 1 error(s) occurred:
> 
> * module.vault.module.vault_elb.aws_elb.vault: 1 error(s) occurred:
> 
> * aws_elb.vault: ValidationError: Only one of SubnetIds or AvailabilityZones may be specified
> 	status code: 400, request id: f23945f5-bee4-11e7-9c0d-6fae286bcbde
> 

By commenting out the subnets-part and just leaving the availability zones it seems to work. 

```
resource "aws_elb" "vault" {
  name = "${var.name}"

  internal                    = "${var.internal}"
  cross_zone_load_balancing   = "${var.cross_zone_load_balancing}"
  idle_timeout                = "${var.idle_timeout}"
  connection_draining         = "${var.connection_draining}"
  connection_draining_timeout = "${var.connection_draining_timeout}"

  security_groups    = ["${aws_security_group.vault.id}"]
  # This split-join hack is a workaround for 'conditional operator cannot be used with list values' typecheck error.
  availability_zones = ["${split(",", length(var.availability_zones) == 0 ? join(",", data.aws_subnet.subnet.*.availability_zone) : join(",", var.availability_zones))}"]
  #subnets            = ["${var.subnet_ids}"]
```

Is this a proper fix? If so, I'll create a PR

**Comment by brikis98** [comment]
Commenting out subnets is not the right fix here. The [ELB docs](http://docs.aws.amazon.com/cli/latest/reference/elb/create-load-balancer.html) indicate you should be able to specify both AZs and subnets, so the error message you're getting is a bit perplexing. Perhaps the AZs and subnets you're specifying don't match up? There should be one AZ per subnet.

Could you show me how you're using the ELB module?

**Comment by flapp** [comment]
I'm using it like in the codeblock at the top. 
Basically I am just using the vault terraform registry module and instantiating this. Not calling the aws_elb module explicitly. So I don't even specify an AZ or a subnet since the module only allows for specifying 'aws_region'

**Comment by brikis98** [comment]
Oh, you're right, that is broken. Looking into it...

**Comment by brikis98** [comment]
OK, I've reverted the change in #20 and released https://github.com/hashicorp/terraform-aws-vault/releases/tag/v0.0.8. I've re-opened #19, which is annoying, but harmless. This issue should now be fixed.
