### ISSUE TITLE
latest ami does not have the latest run-vault script

### ISSUE THREAD

**Issue by Hax7** [hashicorp/terraform-aws-vault#216]
Latest ami does not have the latest run-vault script, I was building a vault cluster based on dynamodb as a storage and I found out that the run-vault script in the ami lacks the required options for dynamo which will cause the user data template to fail and vault service won't be run, I had to go and change the script manually and run the user data script again for vault to work.

**Comment by brikis98** [comment]
What version of the AMI? What version of the repo?

**Comment by Hax7** [comment]
> What version of the AMI? What version of the repo?

ami-0734d9ea03e3ad8bc(ubuntu 16), Master

**Comment by brikis98** [comment]
You're right, there's something wrong with the publishing step of our CI process... I think it's being skipped. Looking into it...

**Comment by brikis98** [comment]
Working on a fix in https://github.com/hashicorp/terraform-aws-vault/pull/219.

**Comment by brikis98** [comment]
OK, I believe the build has been fixed and new artifacts have been published. Could you try again?
