### ISSUE TITLE
Remove availability_zones from autoscaling group

### ISSUE THREAD

**Issue by damonconway** [hashicorp/terraform-aws-vault#220]
I am getting a failure with the autoscaling group when using the vault-cluster submodule. I get an error telling me that it is no longer allowed to specify both availability_zones and vpc_zone_identifier. Since this module requires both availability_zones and subnet_ids to be passed, it seems that we should not pass availability_zones to the autoscaling_group.

Here is the PR in the aws provider that made the change:
https://github.com/terraform-providers/terraform-provider-aws/pull/12927

Terragrunt version: 0.23.33
Terraform version: 0.12.29
Vault module version: 0.13.11
Submodule: vault-cluster

![Screenshot from 2020-09-20 14-13-42](https://user-images.githubusercontent.com/1302982/93719955-90e0ec00-fb4b-11ea-835e-fd8d428f06b4.png)

**Comment by brikis98** [comment]
> Since this module requires both availability_zones and subnet_ids to be passed, it seems that we should not pass availability_zones to the autoscaling_group.

It does NOT require both to be passed. Both are set to `null` by default. If you pass just one or the other, it should work. Could you try?

**Comment by damonconway** [comment]
Ah yes I see that in the variables.tf. The documentation on the registry is wrong then. It lists availability_zones and subnet_ids as required inputs.

https://registry.terraform.io/modules/hashicorp/vault/aws/0.13.11/submodules/vault-cluster?tab=inputs

**Comment by damonconway** [comment]
I can also confirm that not passing availability_zones, the module works as expected now. I'll close my PR out. Should I open a new issue for the documentation problem?

**Comment by brikis98** [comment]
> Ah yes I see that in the variables.tf. The documentation on the registry is wrong then. It lists availability_zones and subnet_ids as required inputs.
> 
> https://registry.terraform.io/modules/hashicorp/vault/aws/0.13.11/submodules/vault-cluster?tab=inputs

Hm, seems like a bug in the registry, no?

**Comment by brikis98** [comment]
No response in a few months. Closing.
