### ISSUE TITLE
"Releases Page" link -> Github 404 page

### ISSUE THREAD

**Issue by boldandbusted** [hashicorp/terraform-aws-vault#24]
On https://github.com/hashicorp/terraform-aws-vault/tree/master/examples/vault-consul-ami/README.md, last link 404s, sadly. Cheers.

**Comment by brikis98** [comment]
Fixed! https://github.com/hashicorp/terraform-aws-vault/commit/0734c30fa20892b4892ec9aed1a6564a9fed39e8
