### ISSUE TITLE
Upgrading private vault cluster

### ISSUE THREAD

**Issue by ducthien1490** [hashicorp/terraform-aws-vault#244]
I built a HA, private vault/consul cluster based on `vault-cluster-private` example 2 years ago.
Now I want to update both  private AMI and vault/consul version.
What should I do to upgrade and keep everything safe?

**Comment by brikis98** [comment]
1. Figure out what version of this repo you used: look for `version = "xxx"` or `?ref=xxx`.
1. Go to the [release notes](https://github.com/hashicorp/terraform-aws-vault/releases).
1. Follow the upgrade instructions in each release.

**Comment by ducthien1490** [comment]
@brikis98 Thanks!
