### ISSUE TITLE
Allow specification of non-default VPC

### ISSUE THREAD

**Issue by boldandbusted** [hashicorp/terraform-aws-vault#25]
The Consul TF Registry module allows this. I think I see what changes were made there, and I hope I can make a PR that holds equivalent changes for this module (and how it uses the Consul module itself). I know that the code in the root of this repo is for "examples" and "testing", but I want to be fully lazy and have it also work for a real production setup as well as for testing purposes. ;)

**Comment by brikis98** [comment]
It might be better to create another folder under `examples` that contains a more production-ready module.

**Comment by boldandbusted** [comment]
See #26. :)

**Comment by jasonmcintosh** [comment]
https://github.com/hashicorp/terraform-aws-vault/pull/39 should now have this fixed?

**Comment by brikis98** [comment]
Yes, both examples now allow you to use a non-default VPC.
