### ISSUE TITLE
database/config always gives a diff

### ISSUE THREAD

**Issue by anshprat** [hashicorp/terraform-aws-vault#32]
Hi,

With the below module, database/config path always gives a diff after first apply:

```

resource "vault_generic_secret" "db_config" {
  count = "${local.is_mysql}"
  path  = "database/config/${var.db_identifier}"

  data_json = <<EOT
{
  "plugin_name":"mysql-database-plugin",
   "connection_url":"${var.db_user}:${var.db_creds}@tcp(${var.rds_name}:3306)/",
    "allowed_roles":["${var.db_role}_rw","${var.db_role}_ro"]
}
EOT
}

```

This happens as on the vault side, connection_url is actually an object inside connection_details. so changing the data_json to:

```

  data_json = <<EOT
{
  "plugin_name":"mysql-database-plugin",
  "connection_details":
    {"connection_url":"${var.db_user}:${var.db_creds}@tcp(${var.rds_name}:3306)/"} ,
    "allowed_roles":["${var.db_role}_rw","${var.db_role}_ro"]
}

```

fixes the diff after creating the config. However, with the above json, new configs cannot be created as vault throws error saying

* error creating database object: connection_url cannot be empty

**Comment by brikis98** [comment]
It looks like this is a bug with the Vault provider. This repo is for a Terraform module to run Vault, but not the provider itself. You probably want to file this bug in: https://github.com/terraform-providers/terraform-provider-vault
