### ISSUE TITLE
How to configure Vault path

### ISSUE THREAD

**Issue by Toady00** [hashicorp/terraform-aws-vault#33]
I've successfully deployed this module and your work is greatly appreciated. But I'm curious, if I want to run multiple vault clusters, for example a non-prod and a prod cluster, but connected to the same consul cluster, I imagine I need to set the vault path, but I'm not sure where that option exists.

I've seen in the run-vault script there is an option to specify a vault config file. How does that work? I'm assuming the cli options take precedence and since I don't see a vault path arg that should work right? My bigger question though is, is there any documentation on the best way to deploy the config file? I don't want to have to have separate packer built AMIs for each vault path I need to support. Is there an preferred way to deploy that config, and is that the only way to set the vault path?

**Comment by brikis98** [comment]
Docs on overriding the config are here: https://github.com/hashicorp/terraform-aws-vault/tree/master/modules/run-vault#overriding-the-configuration

**Comment by Toady00** [comment]
Not sure how I missed that. Thanks!

**Comment by brikis98** [comment]
You're welcome! :)
