### ISSUE TITLE
Support tagged lookups on VPC & Subnets

### ISSUE THREAD

**Issue by jasonmcintosh** [hashicorp/terraform-aws-vault#38]
For systems NOT using the default vpc (e.g. using the terraform vpc module), there are often public and private subnets created.  This means 6 subnets 2 per AZ, which breaks this module.  One thought is to add a variable
```
variable "subnet_tags" {
##   Tier = "Private"

}
```
and modify main.tf to do
```
data "aws_subnet_ids" "default" {
  vpc_id = "${data.aws_vpc.default.id}"
  tags = "${var.subnet_tags}"
}
```
Then apply similar logic to the aws_vpc block

**Comment by brikis98** [comment]
Assuming that Terraform treats an empty `tags` value the same as no value at all, I'm definitely in favor of this change!

**Comment by jasonmcintosh** [comment]
:)  NULL != 0 != "" != [] != {} :)

**Comment by brikis98** [comment]
Haha, yep. I even filed a bug about it: https://github.com/hashicorp/terraform/issues/14037

**Comment by jasonmcintosh** [comment]
https://github.com/hashicorp/terraform-aws-vault/pull/39 :)

**Comment by patoarvizu** [comment]
#39 Adds support for tagged lookups on the main "example", but not on the `vault-cluster` module, which is where I think would be more valuable, since the main example is not one-size-fits-all. Plus I don't think examples are supposed to be considered production-ready anyway (or at least they should be considered less production-ready than modules). I'll open an issue for it.

**Comment by jasonmcintosh** [comment]
@patoarvizu vpc_id in the vault-cluster module is just a variable. It's up to the client depending on it as a module to set it.  Either through a data lookup or similar.  The main is an example implementation of how to do so.  In theory, you could pass a set of filters or tags instead of the vpc_id but that starts to complicate the module.  This way you can do any of the available options.
