### ISSUE TITLE
Vault-elb: Error reading secret/foo: Get https://<dns_name>/v1/secret/foo: dial tcp <ip>:443: i/o timeout

### ISSUE THREAD

**Issue by ksandrmatveyev** [hashicorp/terraform-aws-vault#50]
Hi, Got the issue `Error reading secret/foo: Get https://<dns_name>/v1/secret/foo: dial tcp <ip>:443: i/o timeout` when using of vault-elb module. Got the same thing for each instance from CIDR blocks for Vault security groups (ELB, LC). Certificate was generated for route53 of vault-elb (via private-tls-cert module)

**Comment by brikis98** [comment]
Did you initialize and unseal the cluster?

**Comment by ksandrmatveyev** [comment]
Yes, of course. I'm just try to login from another instance/workstation via different auth methods and get this

**Comment by brikis98** [comment]
Does it work if you SSH to a server and try to read a secret over localhost?

**Comment by ksandrmatveyev** [comment]
Yeap. Just via root token I can read/write secrets then. When I try to use vault on other machine via -address=<elb_name> I got i/o timeout. Basic health check works

**Comment by brikis98** [comment]
Sounds like a security group issue. What ports/IPs are allowed to talk to your Vault ELB's security group?

**Comment by ksandrmatveyev** [comment]
Yes. You are right. Sorry for confusion. Used wrong sg rule for elb instead of 443:443(tcp). Can be closed

**Comment by brikis98** [comment]
Thx for following up!
