### ISSUE TITLE
Routing Traffic via the ELB to the Standby nodes?

### ISSUE THREAD

**Issue by mlcooper** [hashicorp/terraform-aws-vault#54]
Hi. :wave: 

In your ELB module documentation you state the following: 
```
Health Check: The ELB uses the /sys/health endpoint on your Vault servers, with the standbyok flag set to true, as a health check endpoint. This way, the ELB will see any primary or standby Vault node that is unsealed as healthy and route traffic to it.
```
My question is that with this configuration you're going to route traffic to the `*standby*` nodes as well because they're going to be marked as Healthy by the ELB.  Will `standby` nodes accept requests from the ELB?  Will they be serviced properly?  I was under the assumption that ONLY the Primary node should have traffic routed to it.  

I am using consul as a backend, and my `advertise_addr` is set to `http://127.0.0.1`.

**Comment by brikis98** [comment]
Hi there! 👋

`standby` nodes should forward requests on to the primary, so while not the most efficient solution, it should still work OK with a load balancer.

**Comment by mlcooper** [comment]
Thanks.  Do standbys forward by default or is there a particular parameter I need to configure?

On Apr 6, 2018, at 6:47 PM, Yevgeniy Brikman <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi there! 👋

standby nodes should forward requests on to the primary, so while not the most efficient solution, it should still work OK with a load balancer.

**Comment by brikis98** [comment]
https://www.vaultproject.io/docs/configuration/index.html#high-availability-parameters
