### ISSUE TITLE
module/private-tls-cert - IP Addresses Requirement

### ISSUE THREAD

**Issue by karma0** [hashicorp/terraform-aws-vault#66]
Is there a way to get around the IP addresses requirement in the `private-tls-cert` module?  I'm generating ASG clusters using `terraform` in AWS, and it would be beneficial to use domains with wildcards instead of IP's since everything is generated on the fly.

My only other options seem to be:

- Include the module in my project, then generating everything together (putting the private key in the remote state file) in order to dynamically generate the IP list
- Set up an ELB with an elastic IP, which makes my cluster public

Is there another way?

**Comment by brikis98** [comment]
Have you tried setting it to an empty list?

**Comment by karma0** [comment]
That may very well be the first thing that I tried.  I also tried removing the variable completely from `private-tls-cert` given that `ip_addresses` is an optional field to the `tls_cert_request` resource.  Unfortunately, both of these changes result in a 'SAN IP` error in response to engaging with the server:

```
Error initializing: Put https://127.0.0.1:8200/v1/sys/init: x509: cannot validate certificate for 127.0.0.1 because it doesn't contain any IP SANs
```

Adding `127.0.0.1` to the list fixes this issue for `vault operator init`, _but_ it doesn't help when the `nomad-cluster` or any other services are trying to engage from dynamic addresses.

The only immediate solution that comes to mind is to create a `*.tf` file that gets auto-generated with all IPs that are dynamically allocated under a class B VPC -- 65536 in total, minus the few network, broadcast, and gateway IPs which I wouldn't expect the certs to allow in this case.

**Comment by brikis98** [comment]
AFAIK, TLS certs are issued for IPs or domain names. You can't issue one for "all IPs" or "all domain names." Therefore, you have several options:

1. Create TLS certs that match the domain name your Vault nodes register in the Consul agent. E.g., `vault-0.service.consul`, `vault-1.service.consul`, etc. See [dnsmasq](https://github.com/hashicorp/terraform-aws-consul/tree/master/modules/install-dnsmasq).

1. Attach DNS names to each Vault node using [Route 53 private hosted zones](https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/hosted-zones-private.html) and issue TLS certs for these same internal domain names. 

1. Attach an [ENI](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html) to each Vault server to give it a static IP and issue a TLS cert for the same IP.

**Comment by karma0** [comment]
Thanks for the feedback.  I see what I was missing: the reverse lookup on the IP addresses was key in allowing the clients to connect.  The following configuration parameters resolved it for me:
```
ip_addresses = ["127.0.0.1"]
dns_names = ["*.consul", "active.vault.service.consul"]
```
The `*.consul` was the key here, since forward lookup on services was `*.service.consul` and reverse lookup was `*.<zone>.consul
Also, I hadn't realized that ENI was a thing, that's good to know.
Thanks!
