### ISSUE TITLE
Use systemd instead of supervisord

### ISSUE THREAD

**Issue by marek-obuchowicz** [hashicorp/terraform-aws-vault#73]
On systems which have systemd available (more and more...), systemd might be used instead of supervisord. It saves runtime resources (no need to run supervisord and systemd at the same tie) and speeds up installation, hepful for autoscaling groups without pre-baked images.

**Comment by brikis98** [comment]
Agreed it would be nice to standardize on systemd. The limitation before was Amazon Linux, which did not support it, and was an important use case for AWS. Amazon Linux 2 does support systemd, so once the final version of that is released, and Amazon Linux 1 is no longer a mainstream AMI, I think we can migrate to systemd.
