### ISSUE TITLE
dynamodb backend

### ISSUE THREAD

**Issue by BonzTM** [hashicorp/terraform-aws-vault#76]
I noticed that DDB isn't a backend choice in the module.  With DDB now having an SLA I think it would be useful as an HA backend without needing Consul.  I've deployed this module in the enterprise and added the functionality.

**Comment by BMonsalvatge** [comment]
This is actually something I've already had the need to work on.  Hopefully I can clean things up a bit and submit a PR.

**Comment by BonzTM** [comment]
BMonsalvatge,
I have a PR open at the moment for this very thing.  See if it encompasses your needs or if anything needs changed or added

**Comment by BMonsalvatge** [comment]
BonzTM,

Awesome,  just pulled the latest commit and tested it out with the `vault-elb` module in front of it.  Seems to be working great!  

I'll do some more manual testing and let you know if I find any issues.  With the addition of this enhancement, it may be worth adjusting or creating an AMI example without consul.  At least documented on the existing one so it's not needlessly installed in the AMI.

I can submit a PR on that separately if that's not already taken care of and I just missed it..

**Comment by BonzTM** [comment]
@BMonsalvatge ,
I've included your changes into my PR per your review.  Personally I made this enhancement because I had no use for Consul and I am not using packer but rather installing/configuring during user-data at fresh boot every time.  Unfortunately it's not already taken care of in this PR and probably could be a separate if needed.
