### ISSUE TITLE
Need to add tags to the remaining taggable resources

### ISSUE THREAD

**Issue by jcejohnson** [hashicorp/terraform-aws-vault#85]
Similar to my recent [PR](https://github.com/hashicorp/terraform-aws-vault/pull/81), I have a need to apply tags to all taggable resources (corporate policy). I have a [commit](https://github.com/EFXCIA/terraform-aws-vault/commit/29008ebc21ee2e6af6f153793fe0d90018aa1b1e) on our fork and will be submitting a PR as soon as I test it in our environment.

**Comment by brikis98** [comment]
Sounds good!

**Comment by jcejohnson** [comment]
https://github.com/hashicorp/terraform-aws-vault/pull/86
